backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/openarchiefbeheer/api/authentication/authentication.py, backend/src/openarchiefbeheer/api/authentication/serializers.py, backend/src/openarchiefbeheer/api/authentication/urls.py, backend/src/openarchiefbeheer/api/authentication/views.py, backend/src/openarchiefbeheer/api/tests/test_authentication_endpoints.py, backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/conf/base.py, backend/src/openarchiefbeheer/middleware.py, backend/src/openarchiefbeheer/urls.py
Fixes https://github.com/maykinmedia/archiefbeheercomponent/issues/340 (partially)
=> Authentication endpoints

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/openarchiefbeheer/conf/base.py, backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py, backend/src/openarchiefbeheer/logging/logevent.py, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_created.txt
Addition to https://github.com/maykinmedia/archiefbeheercomponent/issues/340
=> Add logging

backend/src/openarchiefbeheer/zaken/tests/factories.py
=> [#25] Add traits to factory

backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/zaken/api/views.py, backend/src/openarchiefbeheer/zaken/tests/test_views.py
=> [#11] Caching zaken endpoint

backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/zaken/api/serializers.py, backend/src/openarchiefbeheer/zaken/api/views.py, backend/src/openarchiefbeheer/zaken/tests/test_views.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#32] Zaaktypen choices endpoint

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/src/openarchiefbeheer/conf/base.py, backend/src/openarchiefbeheer/zaken/api/serializers.py, backend/src/openarchiefbeheer/zaken/tests/test_tasks.py
=> [#41] Retrieve zaken with geometry

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/requirements/test-tools.in, backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/destruction/api/filtersets.py, backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py
Fixes #45 (partially)
This adds the endpoint to retrieve destruction list and the items so that they can be displayed in the destruction list detail view.
=> Endpoints destruction list items

backend/src/openarchiefbeheer/destruction/admin.py, backend/src/openarchiefbeheer/destruction/api/serializers.py
=> [#51] Return 'created' field for the destruction list

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py, backend/src/openarchiefbeheer/logging/logevent.py, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_updated.txt
Fixes #45 (partially)
This adds the endpoint to partially/fully update a destruction list
=> [#45] Update list endpoint

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py, backend/src/openarchiefbeheer/zaken/api/filtersets.py, backend/src/openarchiefbeheer/zaken/tests/test_viewsets.py
Fixes #45 (partially)
Some things that came up while implementing the frontend.
=> [#45] Improvements backend

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py
=> [#58] Validate double reviewer

frontend/src/pages/landing/Landing.tsx
=> [#75] Add redirect to log in if user not logged in

.gitignore, backend/src/openarchiefbeheer/zaken/api/filtersets.py, backend/src/openarchiefbeheer/zaken/api/serializers.py, backend/src/openarchiefbeheer/zaken/tasks.py, backend/src/openarchiefbeheer/zaken/tests/test_viewsets.py, frontend/src/pages/destructionlist/create/DestructionListCreate.tsx, frontend/src/pages/destructionlist/detail/DestructionListDetail.stories.tsx, frontend/src/pages/destructionlist/hooks.ts, frontend/src/types.d.ts
=> [#63] Behandelend afdeling filter

backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py
=> Fix problem of not being able to accept a list

backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/destruction/migrations/0007_destructionlistreview_destructionlistitemreview.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/zaken/api/serializers.py, backend/src/openarchiefbeheer/zaken/api/views.py, backend/src/openarchiefbeheer/zaken/tests/factories.py, backend/src/openarchiefbeheer/zaken/tests/test_views.py, backend/src/openarchiefbeheer/zaken/types.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#127] Selectielijstklasse choices endpoint

backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/destruction/api/filtersets.py, backend/src/openarchiefbeheer/destruction/api/permissions.py, backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/factories.py, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py
Fixes #127 (partially)
Added the endpoint to create a response to a review.
=> [#127] Create a response to a review

frontend/src/components/DestructionList/DestructionList.tsx, frontend/src/lib/zaakSelection/zaakSelection.ts, frontend/src/pages/destructionlist/hooks.ts, frontend/src/pages/destructionlist/hooks.tsx, frontend/src/pages/destructionlist/review/DestructionListReview.tsx
=> :sparkles: #120 - feat: implemented comments

backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tasks.py, backend/src/openarchiefbeheer/destruction/tests/factories.py, backend/src/openarchiefbeheer/destruction/tests/test_tasks.py
=> [#111] Assign first reviewer after changes are processed

backend/src/openarchiefbeheer/destruction/tasks.py, backend/src/openarchiefbeheer/destruction/tests/test_tasks.py
Fixes #111 
Forgot to update the status of the destruction list in the previous PR
=> [#111] Status update after reassiging first reviewer

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py, backend/src/openarchiefbeheer/logging/logevent.py, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_reviewed.txt
=> [#82] Log when a list is reviewed

backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/config/api/serializers.py, backend/src/openarchiefbeheer/config/api/views.py, backend/src/openarchiefbeheer/config/tests/test_views.py
=> [#81] Endpoints for archive config

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py
=> [#81] Logic for long/short procedure 

.github/workflows/ci.yml
=> [#190] Fix codecov failing to upload report

frontend/src/pages/landing/Landing.tsx
=> :art: - fix: tooltip on bottom instead of top

frontend/src/pages/destructionlist/create/components/DestructionList/DestructionList.tsx
=> :art: - fix: fixed primary button

backend/package-lock.json, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt
=> Upgrade packages

backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_destroy.py, backend/src/openarchiefbeheer/utils/tests/gherkin.py, frontend/package-lock.json, frontend/package.json, frontend/src/lib/api/destructionLists.ts, frontend/src/lib/api/request.ts, frontend/src/lib/auth/loaders.ts, frontend/src/lib/auth/permissions.ts, frontend/src/pages/destructionlist/detail/DestructionListDetail.action.ts, frontend/src/pages/destructionlist/detail/DestructionListDetail.loader.ts, frontend/src/pages/destructionlist/detail/DestructionListDetail.stories.tsx, frontend/src/pages/destructionlist/detail/DestructionListDetail.tsx, frontend/src/pages/landing/Landing.tsx
depends on: https://github.com/maykinmedia/admin-ui/pull/111 release
closes #95
=> :sparkles: #95 - feat: implement destroy action on the frontend

frontend/src/pages/destructionlist/hooks/useDataGridProps.tsx
=> :art: - fix: changed the date formatting

backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/destruction/tests/test_utils.py, backend/src/openarchiefbeheer/destruction/utils.py
=> [#263] Add ordering of assignees to destruction list endpoint

backend/src/openarchiefbeheer/destruction/exceptions.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tasks.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py, backend/src/openarchiefbeheer/destruction/tests/test_signals.py, backend/src/openarchiefbeheer/destruction/tests/test_tasks.py, backend/src/openarchiefbeheer/destruction/utils.py
=> [#229] Continue deleting if a case fails

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx
depens on release of: https://github.com/maykinmedia/admin-ui/pull/120
=> :lipstick: - style: alter logo styling in sidebar

backend/src/openarchiefbeheer/destruction/api/permissions.py, backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/assignment_logic.py, backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_mark_ready_to_review.py, backend/src/openarchiefbeheer/destruction/tests/factories.py, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py, backend/src/openarchiefbeheer/logging/logevent.py, backend/src/openarchiefbeheer/utils/tests/gherkin.py, frontend/src/lib/api/destructionLists.ts, frontend/src/lib/auth/permissions.ts, frontend/src/lib/format/user.ts, frontend/src/pages/constants.tsx, frontend/src/pages/destructionlist/detail/DestructionListDetail.action.ts, frontend/src/pages/destructionlist/detail/DestructionListDetail.loader.ts, frontend/src/pages/destructionlist/detail/DestructionListDetail.tsx, frontend/src/pages/destructionlist/detail/components/DestructionListEdit/DestructionListEdit.tsx, frontend/src/pages/destructionlist/detail/components/DestructionListToolbar/DestructionListToolbar.tsx, frontend/src/pages/landing/Landing.tsx
=> [#235] Mark list as ready to review

backend/src/openarchiefbeheer/zaken/tests/test_views.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#303] Handle empty zaaktype identificatie

backend/src/openarchiefbeheer/zaken/tests/test_views.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#303] Handle empty identificatie also if query params are present

backend/src/openarchiefbeheer/destruction/admin.py, frontend/src/components/ProcessingStatusBadge/ProcessingStatusBadge.tsx, frontend/src/components/ProcessingStatusBadge/index.ts, frontend/src/components/index.ts, frontend/src/fixtures/destructionListItem.ts, frontend/src/lib/api/destructionListsItem.ts, frontend/src/pages/ProcessingStatusBadge.tsx, frontend/src/pages/destructionlist/detail/DestructionListDetail.stories.tsx, frontend/src/pages/destructionlist/detail/DestructionListDetail.tsx, frontend/src/pages/destructionlist/detail/components/DestructionListEdit/DestructionListEdit.tsx, frontend/src/pages/destructionlist/hooks/useDataGridProps.tsx, frontend/src/pages/landing/Landing.tsx
=> [#229] Show number failed zaken

backend/src/openarchiefbeheer/conf/locale/nl/LC_MESSAGES/django.po, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/destruction/tests/test_serializers.py, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_created.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_finalized.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_reassigned.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_reviewed.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_updated.txt
Fixes https://dimpact.atlassian.net/jira/software/c/projects/PZ/boards/258?selectedIssue=PZ-3719
=> Fix backend translations

backend/bin/celery_beat.sh
=> [#351] Fix starting beat scheduler

.gitignore, backend/src/openarchiefbeheer/accounts/admin.py
=> [#352] Fix admin role list page

backend/docs/developers/logic.rst, backend/src/openarchiefbeheer/config/exceptions.py, backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_process_review.py, backend/src/openarchiefbeheer/destruction/tests/endpoints/test_reviewresponse.py, backend/src/openarchiefbeheer/destruction/tests/serializers/test_reviewresponse.py, backend/src/openarchiefbeheer/destruction/tests/vcr/cassettes/ReviewResponseSerializerTest.test_new_selectielijst_blijvend_bewaren.yaml, backend/src/openarchiefbeheer/destruction/tests/vcr/test_serializers.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#386] Checks for selectielijstklasse waardering "blijvend bewaren" [Backend]

backend/src/openarchiefbeheer/zaken/api/viewsets.py
=> [#393] Add ordering to zaken endpoint

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py, backend/src/openarchiefbeheer/zaken/api/serializers.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#397] Save zaak metadata before deletion

backend/src/openarchiefbeheer/emails/admin.py, backend/src/openarchiefbeheer/emails/tests/test_admin.py
=> [#419] Broken email admin page

backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tasks.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py, backend/src/openarchiefbeheer/destruction/tests/test_tasks.py
=> [#397] Delete local metadata

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/tests/endpoints/test_abort_destruction.py, backend/src/openarchiefbeheer/logging/logevent.py, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_aborted.txt
=> [#484] Log abort destruction

backend/src/openarchiefbeheer/destruction/api/viewsets.py, backend/src/openarchiefbeheer/destruction/tests/endpoints/test_co_reviewers.py, backend/src/openarchiefbeheer/selection/api/views.py, backend/src/openarchiefbeheer/selection/tests/test_endpoints.py
=> [#493] Fix OPTIONS endpoints 

backend/src/openarchiefbeheer/selection/api/schemas.py, backend/src/openarchiefbeheer/selection/api/views.py
=> :bug: [#508] Fix API schema

backend/requirements/base.in, backend/requirements/base.txt, backend/requirements/ci.txt, backend/requirements/dev.txt, backend/requirements/test-tools.in, backend/src/openarchiefbeheer/destruction/destruction_report.py, backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py, backend/src/openarchiefbeheer/destruction/tests/test_tasks.py, backend/src/openarchiefbeheer/destruction/tests/vcr/cassettes/CreateDestructionReportTest.test_create_destruction_report.yaml, backend/src/openarchiefbeheer/destruction/utils.py, backend/src/openarchiefbeheer/zaken/api/constants.py, backend/src/openarchiefbeheer/zaken/api/serializers.py
=> [#502] Make destruction report xlsx file instead of csv

backend/src/openarchiefbeheer/logging/tests/test_logevent.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#539] Handle no resultaat on zaak

frontend/src/components/DestructionListAuditLog/DestructionListAuditLog.tsx, frontend/src/components/DestructionListReviewer/DestructionListReviewer.tsx, frontend/src/components/DestructionListToolbar/DestructionListToolbar.tsx, frontend/src/hooks/useAuditLog.ts, frontend/src/lib/api/auditLog.ts
closes #498 
- Checked that the entries wit the same timestamps are all present
Depends on Admin UI update (https://github.com/maykinmedia/admin-ui/pull/155)
=> :sparkles: - feat: implemented the audit log addition

backend/src/openarchiefbeheer/conf/locale/nl/LC_MESSAGES/django.po
=> :bug: - fix: typo

frontend/src/hooks/useZaakReviewStatusBadges.tsx
=> :bug: - fix: changed if/else conditions

.readthedocs.yaml
Otherwise it takes the dev settings
=> :construction: Override env var for building docs

backend/docs/conf.py
Otherwise the dev settings are used
=> :construction: Still try to override the env vars

backend/src/openarchiefbeheer/destruction/api/viewsets.py
=> :memo: [#537] Fix API docs

backend/src/openarchiefbeheer/destruction/api/serializers.py, backend/src/openarchiefbeheer/destruction/tests/endpoints/test_destructionlist.py
=> [#599] Check destruction list author

backend/docker-services/openzaak/fixtures/complex_relations.json, backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/zaken/api/mixins.py, backend/src/openarchiefbeheer/zaken/api/serializers.py, backend/src/openarchiefbeheer/zaken/api/views.py, backend/src/openarchiefbeheer/zaken/tests/test_tasks.py, backend/src/openarchiefbeheer/zaken/tests/vcr/cassettes/ExternalZaaktypenChoicesViewTests.test_retrieve_all_choices.yaml, backend/src/openarchiefbeheer/zaken/tests/vcr/cassettes/InformatieobjecttypenChoicesViewTests.test_retrieve_all_choices.yaml, backend/src/openarchiefbeheer/zaken/tests/vcr/cassettes/InformatieobjecttypenChoicesViewTests.test_retrieve_choices_with_filters.yaml, backend/src/openarchiefbeheer/zaken/tests/vcr/cassettes/ResultaattypenChoicesViewTests.test_retrieve_all_choices.yaml, backend/src/openarchiefbeheer/zaken/tests/vcr/cassettes/ResultaattypenChoicesViewTests.test_retrieve_choices_with_filters.yaml, backend/src/openarchiefbeheer/zaken/tests/vcr/cassettes/StatustypenChoicesViewTests.test_retrieve_all_choices.yaml, backend/src/openarchiefbeheer/zaken/tests/vcr/cassettes/StatustypenChoicesViewTests.test_retrieve_choices_with_filters.yaml, backend/src/openarchiefbeheer/zaken/tests/vcr/test_views.py, backend/src/openarchiefbeheer/zaken/utils.py
Partly Fixes #553
Needed by https://github.com/maykinmedia/open-archiefbeheer/pull/604
=> [#553] Update choices endpoints

backend/src/openarchiefbeheer/config/tests/test_views.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py, backend/src/openarchiefbeheer/destruction/utils.py
=> [#553] Make resultaattype statustype really optional

backend/src/openarchiefbeheer/accounts/templatetags/format_user.py, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_aborted.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_co_reviewed.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_co_reviewers_added.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_created.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_deletion_triggered.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_finalized.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_ready_for_first_review.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_reassigned.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_review_response_created.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_reviewed.txt, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_updated.txt
=> [#530] Use extra_data for user in log

frontend/.storybook/mockData.ts, frontend/src/pages/landing/Landing.stories.tsx
=> :white_check_mark: - test: expanded test

backend/docs/developers/vcr-tests.rst, backend/src/openarchiefbeheer/conf/base.py, backend/src/openarchiefbeheer/utils/utils_decorators.py
=> [#208] Improve docker reload fixture decorator

backend/docs/devops/2fa.rst, backend/docs/devops/index.rst, backend/src/openarchiefbeheer/conf/base.py
=> [#177] 2fa settings

backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/conf/locale/nl/LC_MESSAGES/django.po, backend/src/openarchiefbeheer/config/api/views.py, backend/src/openarchiefbeheer/config/health_checks.py, backend/src/openarchiefbeheer/config/tests/test_health_checks.py, backend/src/openarchiefbeheer/config/tests/test_views.py, backend/src/openarchiefbeheer/config/tests/vcr/cassettes/TestConfigurationHealthChecks.test_correctly_configured.yaml, backend/src/openarchiefbeheer/config/tests/vcr/test_health_checks.py
=> [#595] Add backend health checks

backend/docs/manual/3-administrator/3.1-email-templates.rst
=> [#717] Document no emails being sent if templates not configured

backend/src/openarchiefbeheer/destruction/models.py, backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_configure_destruction_report.py, backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_configure_short_procedure.py, backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_review.py, backend/src/openarchiefbeheer/destruction/tests/test_assignement_logic.py, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/destruction/tests/test_models.py, backend/src/openarchiefbeheer/utils/tests/gherkin.py
=> [#755] Fix short procedure

backend/src/openarchiefbeheer/destruction/tests/vcr/cassettes/DestructionTest.test_document_deleted.yaml, backend/src/openarchiefbeheer/zaken/api/views.py, backend/src/openarchiefbeheer/zaken/tests/cassettes/ZaakSerialisersTests.test_selectielijstklasse.yaml, backend/src/openarchiefbeheer/zaken/tests/test_serializer.py, backend/src/openarchiefbeheer/zaken/tests/test_views.py, backend/src/openarchiefbeheer/zaken/utils.py
=> [#729] Add year selectielijstklasse label

.github/workflows/ci.yml, backend/src/openarchiefbeheer/conf/ci.py, backend/src/openarchiefbeheer/conf/dev.py, backend/src/openarchiefbeheer/utils/tests/e2e.py
=> [#773] Try getting tracing on failure

backend/src/openarchiefbeheer/destruction/api/filtersets.py, backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_edit.py
Fixes #773 (I hope)
This PR fixes `openarchiefbeheer.destruction.tests.e2e.features.test_feature_list_edit.FeatureListEditTests.test_scenario_user_edits_multi_page_destruction_list`
=> [#773] Attempt to fix some flakyness

.github/workflows/ci.yml, README.rst
=> [#780] Description project

backend/src/openarchiefbeheer/destruction/tasks.py, backend/src/openarchiefbeheer/destruction/tests/test_tasks.py, frontend/src/components/ProcessingStatusBadge/ProcessingStatusBadge.tsx, frontend/src/lib/format/date.ts
=> [#785] Update date check

backend/src/openarchiefbeheer/conf/locale/nl/LC_MESSAGES/django.po, backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py, backend/src/openarchiefbeheer/logging/logevent.py, backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_ready_for_first_review.txt
=> [#788] Update logs with zaak number

frontend/src/hooks/useFields.tsx
=> :art: [#816] - fix: overflow button is now in zaaktype

backend/src/openarchiefbeheer/api/urls.py, backend/src/openarchiefbeheer/zaken/api/views.py, backend/src/openarchiefbeheer/zaken/tests/test_views.py
=> [#824] Add endpoint to clear cache backend

backend/docs/devops/index.rst, backend/docs/devops/oidc.rst
Added to facilitate keycloak configuration for Dimpact.
=> :memo: Configure which groups are needed in OAB
