maykinmedia/open-archiefbeheer

backend/src/openarchiefbeheer/destruction/api/viewsets.py
backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py

Fixes https://github.com/maykinmedia/archiefbeheercomponent/issues/345
To do: 
- ~Clarify if we want a paginated response for this endpoint~ => Discussed: no pagination

[#345] Destruction list endpoint

---

backend/src/openarchiefbeheer/zaken/api/filtersets.py
backend/src/openarchiefbeheer/zaken/tests/test_viewsets.py
frontend/package-lock.json
frontend/package.json
frontend/src/components/DestructionList/DestructionList.tsx
frontend/src/index.tsx
frontend/src/lib/api/request.ts
frontend/src/lib/api/reviewers.ts
frontend/src/pages/destructionlist/Assignees.tsx
frontend/src/pages/destructionlist/DestructionListCreate.tsx
frontend/src/pages/destructionlist/DestructionListDetail.css
frontend/src/pages/destructionlist/DestructionListDetail.tsx
frontend/src/pages/destructionlist/DestructionListItems.tsx
frontend/src/pages/destructionlist/constants.ts
frontend/src/pages/destructionlist/index.ts
frontend/src/pages/destructionlist/types.ts
frontend/src/pages/destructionlist/utils.ts
frontend/src/pages/landing/Landing.tsx

[#45] Destruction list detail view

---

backend/src/openarchiefbeheer/conf/base.py

This is useful if open-zaak is very slow. Like in our case... I set this value to 5000 for our test environment and I also use this locally if I want to retrieve the zaken from open zaak

Make read timeout configurable

---

backend/src/openarchiefbeheer/destruction/tasks.py

Fixes #155 
We don't want to run in a transaction, because otherwise we loose information about the statuses of the items that have been processed

[#155] Remove select_for_update 

---

backend/src/openarchiefbeheer/zaken/models.py

Fixes #156 
(note: sometimes open-zaak returns a 500 during this operation: https://github.com/open-zaak/open-zaak/issues/1707)

[#156] Use json format for updating zaak

---

docker-nginx-default.conf

Fixes #169 
In the docs of React Router: https://reactrouter.com/en/6.24.1/routers/picking-a-router#web-projects
> If you're hosting your app on a static file server, you'll need to configure it to send all requests to your index.html to avoid getting 404s.
Corresponding change in the chart: https://github.com/maykinmedia/charts/pull/109/commits/a3a597153aed2996f49d1f750f6e75c3cf3e5d21

:bug: [#169] Let react-router handle routes of single page app

---

.github/workflows/ci.yml
Dockerfile
backend/bin/docker_start.sh
backend/dotenv.dev.example
backend/src/openarchiefbeheer/conf/ci.py
backend/src/openarchiefbeheer/conf/dev.py
docker-compose.yml
docker-nginx-default.conf

Partly Fixes #181
The public role of the ansible playbook expects the docker container to expose port 8000.
I think it is also better to be consistent with all the other apps

[#181] Update backend to run on port 8000 by default

---

backend/src/openarchiefbeheer/destruction/api/viewsets.py

[#374] Correct error in API docs

---

backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_review.py
backend/src/openarchiefbeheer/utils/tests/gherkin.py
frontend/src/pages/destructionlist/review/DestructionListReview.tsx

[#372] Reviewer doesnt see all zaken when reviewing for the 2nd time

---

backend/src/openarchiefbeheer/destruction/api/serializers.py
backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_process_review.py
backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_review.py
backend/src/openarchiefbeheer/zaken/admin.py
frontend/src/fixtures/reviewItem.ts
frontend/src/lib/api/review.ts
frontend/src/pages/destructionlist/detail/DestructionListDetail.loader.ts
frontend/src/pages/destructionlist/review/DestructionListReview.loader.ts

[#378] Prevent crash if reviewItem has zaak = null

---

backend/src/openarchiefbeheer/destruction/tests/e2e/features/test_feature_list_process_review.py
frontend/package-lock.json
frontend/package.json
frontend/src/pages/destructionlist/detail/components/DestructionListProcessZaakReviewModal/DestructionListProcessZaakReviewModal.tsx
frontend/src/pages/destructionlist/detail/hooks/useFormDialog.tsx
frontend/src/pages/destructionlist/hooks/useFields.ts

Requires release of: https://github.com/maykinmedia/admin-ui/pull/146
Closes #392

:sparkles: #392 - populate date range filter based on url

---

backend/src/openarchiefbeheer/destruction/api/filtersets.py
backend/src/openarchiefbeheer/destruction/api/serializers.py
backend/src/openarchiefbeheer/destruction/api/viewsets.py
backend/src/openarchiefbeheer/destruction/tests/endpoints/test_destruction_list_items.py
backend/src/openarchiefbeheer/destruction/tests/serializers/test_destruction_list_item.py

Partially fixes #498 
This adds the `review_advice_ignored` field to the destruction list item serialiser and added a `item-order_review_ignored` filter to get the destruction list items that need attention first.

[#498] Add field to Destruction list item serialiser

---

backend/src/openarchiefbeheer/destruction/tasks.py
backend/src/openarchiefbeheer/destruction/tests/test_tasks.py
backend/src/openarchiefbeheer/destruction/utils.py
frontend/src/pages/destructionlist/review/DestructionListReview.action.ts
frontend/src/pages/destructionlist/review/DestructionListReview.tsx

[#498] Pre populate selection after processing review response

---

backend/src/openarchiefbeheer/accounts/tests/factories.py
backend/src/openarchiefbeheer/api/urls.py
backend/src/openarchiefbeheer/conf/locale/nl/LC_MESSAGES/django.po
backend/src/openarchiefbeheer/destruction/api/serializers.py
backend/src/openarchiefbeheer/destruction/api/viewsets.py
backend/src/openarchiefbeheer/destruction/tasks.py
backend/src/openarchiefbeheer/destruction/tests/endpoints/test_reviewresponse.py
backend/src/openarchiefbeheer/destruction/tests/test_endpoints.py
backend/src/openarchiefbeheer/destruction/tests/test_tasks.py
backend/src/openarchiefbeheer/logging/api/filtersets.py
backend/src/openarchiefbeheer/logging/api/serializers.py
backend/src/openarchiefbeheer/logging/api/viewsets.py
backend/src/openarchiefbeheer/logging/logevent.py
backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_ready_for_first_review.txt
backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_review_response_created.txt
backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_review_response_processed.txt
backend/src/openarchiefbeheer/logging/tests/test_endpoints.py
backend/src/openarchiefbeheer/logging/tests/test_logevent.py
backend/src/openarchiefbeheer/zaken/tests/factories.py
backend/src/openarchiefbeheer/zaken/utils.py
frontend/.storybook/mockData.ts
frontend/src/lib/api/auditLog.ts

[#499] Add log when making list ready to review

---

backend/src/openarchiefbeheer/accounts/models.py
backend/src/openarchiefbeheer/accounts/utils.py
backend/src/openarchiefbeheer/destruction/destruction_report.py
backend/src/openarchiefbeheer/destruction/tests/test_models.py
backend/src/openarchiefbeheer/logging/logevent.py
backend/src/openarchiefbeheer/logging/utils.py

Fixes #502
Based on https://github.com/maykinmedia/open-archiefbeheer/pull/525

[#502] Add review process to destruction report

---

backend/bin/setup_configuration.sh
backend/docker-services/keycloak/docker-compose.yaml
backend/docker-services/openzaak/docker-compose.yaml
backend/requirements/base.in
backend/requirements/base.txt
backend/requirements/ci.txt
backend/requirements/dev.txt
backend/src/openarchiefbeheer/conf/base.py
backend/src/openarchiefbeheer/config/setup_configuration/fixtures/data.yaml
docker-compose.yml

[#521] OIDC through django config

---

backend/src/openarchiefbeheer/destruction/api/viewsets.py
backend/src/openarchiefbeheer/destruction/tests/endpoints/test_list_destruction.py
frontend/.storybook/mockData.ts
frontend/src/lib/api/destructionLists.ts
frontend/src/pages/destructionlist/detail/DestructionListDetail.action.ts
frontend/src/pages/destructionlist/detail/hooks/useSecondaryNavigation.tsx

Partially fixed #558 
I think that it makes more sense to have this endpoint be a POST, and then the endpoint that actually deletes the destruction list resource be a DELETE

[#558] Refactor queue destruction endpoint

---

backend/src/openarchiefbeheer/destruction/destruction_report.py
backend/src/openarchiefbeheer/destruction/tests/test_models.py
backend/src/openarchiefbeheer/destruction/tests/test_tasks.py

[#570] Add start of destruction time

---

backend/src/openarchiefbeheer/destruction/tests/test_utils.py
backend/src/openarchiefbeheer/destruction/utils.py
backend/src/openarchiefbeheer/logging/logevent.py
backend/src/openarchiefbeheer/logging/templates/logging/destruction_list_items_deleted.txt

Fixes #544 
We will probably at some point start seeing some race conditions if users interact with the app during a resync :thinking: 
Maybe we need to do something about it

[#544] Delete destruction list items no longer related to a zaak

---

backend/src/openarchiefbeheer/destruction/api/serializers.py
backend/src/openarchiefbeheer/destruction/models.py
backend/src/openarchiefbeheer/destruction/tests/e2e/issues/test_568_correct_count.py
frontend/src/fixtures/destructionList.ts
frontend/src/lib/api/destructionLists.ts
frontend/src/pages/destructionlist/detail/hooks/useSecondaryNavigation.tsx

:bug: #568 - fix: correct count

---

backend/src/openarchiefbeheer/destruction/tests/e2e/issues/test_600_session_expired.py

To give enough time to the test to reach the destruction list detail page before the session is expired.
Fixes #644

[#644] Increase SESSION_COOKIE_AGE in e2e test

---

backend/src/openarchiefbeheer/conf/base.py
backend/src/openarchiefbeheer/destruction/api/viewsets.py
backend/src/openarchiefbeheer/destruction/constants.py
backend/src/openarchiefbeheer/zaken/tests/vcr/test_tasks.py

This is handy for the performance tests, so it doesn't need manual intervention

:wrench: Make waiting period configurable

---

frontend/src/components/DestructionListReviewer/DestructionListReviewer.tsx

:bug: #637 - removed author from selection

---

backend/src/openarchiefbeheer/destruction/api/backends.py
backend/src/openarchiefbeheer/destruction/api/viewsets.py
backend/src/openarchiefbeheer/destruction/tests/e2e/issues/test_667_sorting_seems_to_be_broken.py
backend/src/openarchiefbeheer/utils/tests/gherkin.py
frontend/src/pages/destructionlist/detail/pages/edit/DestructionListEditPage.tsx

@SilviaAmAm this add failing tests for ordering, can you have a look at fixing this?

:test_tube: #667 - test: add (failing) tests for ordering

---

backend/src/openarchiefbeheer/conf/locale/nl/LC_MESSAGES/django.po
backend/src/openarchiefbeheer/config/templates/configuration_health_check.html
backend/src/openarchiefbeheer/config/templatetags/configuration_health_check.py
backend/src/openarchiefbeheer/config/tests/test_admin.py
backend/src/openarchiefbeheer/static/css_overrides/admin_overrides.css
backend/src/openarchiefbeheer/templates/admin/index.html

Partly fixes #595 
Example of successful configuration:
Example with bad configuration:

[#595] Admin checks

---

.github/workflows/build-image.yaml
.github/workflows/ci.yml
Dockerfile
backend/docs/developers/setup-local-env.rst
docker-compose.dev.yml

[#697] Dev docker image to disable 2FA in docker compose
